name: JustHousing
version: '0.0.3'
main: dev.meyba.justHousing.JustHousing
api-version: '1.21'
authors: [ Meyba._., Jezevcik20 ]
description: Just a housing plugin.
commands:
  housing:
    description: Manages housings
    usage: /<command> [create [name]|invite <player>|join <player>|settings|reload|help|list|delete|delete confirm|kick <player> [reason]|ban <player> [reason]|setrole <player> <role>|gamemode creative|adventure|survival [player]]
permissions:
  housing.use:
    description: Allows use of basic housing commands
    default: op
  housing.reload:
    description: Allows reloading the config
    default: op
  housing.help:
    description: Allows a player to see the help menu
    default: true
  housing.create:
    description: Allows creating a housing
    default: op
  housing.delete:
    description: Allows deleting a housing
    default: op
  housing.invite:
    description: Allows inviting players to a housing
    default: op
  housing.join:
    description: Allows joining a player's housing
    default: true
  housing.settings:
    description: Allows opening the housing settings GUI
    default: op
  housing.list:
    description: Allows opening the housing list GUI
    default: true
  housing.gamemode:
    description: Allows changing gamemode of players
    default: op
  housing.time:
    description: Allows changing the housing world time
    default: op
  housing.ban:
    description: Allows to ban players from your housing
    default: op
  housing.unban:
    description: Allows to unban players from your housing
    default: op
  housing.kick:
    description: Allows to kick players from your housing
    default: op
  housing.setrole:
    description: Allows setting member roles in your housing
    default: op
