name: JustHousing
version: '0.0.1'
main: dev.meyba.justHousing.JustHousing
api-version: '1.21'
authors: [ Meyba._. ]
description: Just a housing plugin.
commands:
  housing:
    description: Manages housings
    usage: /<command> [create [name]|invite <player>|join <player>|settings|reload|help|list|delete|delete confirm|kick <player> [reason]|ban <player> [reason]|gamemode creative|adventure|survival [player]]
permissions:
  justhousing.use:
    description: Allows use of basic housing commands
    default: op
  justhousing.reload:
    description: Allows reloading the config
    default: op
  justhousing.help:
    description: Allows a player to see the help menu
    default: true
  justhousing.create:
    description: Allows creating a housing
    default: op
  justhousing.delete:
    description: Allows deleting a housing
    default: op
  justhousing.invite:
    description: Allows inviting players to a housing
    default: op
  justhousing.join:
    description: Allows joining a player's housing
    default: true
  justhousing.settings:
    description: Allows opening the housing settings GUI
    default: op
  justhousing.list:
    description: Allows opening the housing list GUI
    default: true
  justhousing.gamemode:
    description: Allows changing gamemode of players
    default: op
  justhousing.time:
    description: Allows changing the housing world time
    default: op
  justhousing.ban:
    description: Allows to ban players from your housing
    default: op
  justhousing.unban:
    description: Allows to unban players from your housing
    default: op
  justhousing.kick:
    description: Allows to kick players from your housing
    default: op
